### ISSUE TITLE
[BUG] NPM Package not found

### ISSUE THREAD

**Issue by llermaly** [opensearch-project/perftop#18]
**What is the bug?**
NPM Package is not found 

**How can one reproduce the bug?**
1. Run npm install -g @aws/opensearch-perftop

**What is the expected behavior?**
Plugin installed

**What is your host/environment?**
Macos Bigsur

** Error **
Not Found - GET https://registry.npmjs.org/@aws%2fopensearch-perftop

**Comment by Dougems** [comment]
Closest thing I found was https://npms.io/search?q=%40aws%2Fopendistro-for-elasticsearch-perftop, but that's for the open distro (predecessor to OpenSearch), it's 7 months old and wanted an older version of npm:

Unsupported engine for @aws/opendistro-for-elasticsearch-perftop@1.13.0: wanted: {"node":">=10.0.0 <11.0.0"}

**Comment by jianwu** [comment]
npm link is added in the main [OpenSearch documentation](https://opensearch.org/docs/latest/monitoring-plugins/pa/index/), if it's not available in npm registry, please update the opensearch document to avoid confusions?
